### ISSUE TITLE
BulkExecutor should have 1 way non-blocking

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#17]
This seems to be the 1-way version but is blocking:
x.bulk_- execute(f, n, rf, sf)

I like to argue for a 1-way non-blocking version as current SYCL interface can only map to a 1-way non-blocking version, and emulation, we believe is inefficient (e.g. running on a thread would take resource away from SYCL runtime)

**Comment by mjgarland** [comment]
If the caller wants asynchronous execution, they simply need to call bulk_async_execute().

**Comment by AerialMantis** [comment]
I'm not sure this would resolve the requirements for us, from my understanding bulk_async_execute() is also a two-way non-blocking execute function, what we'd like to suggest is a one-way non-blocking executor category with it's own execute function for this case.

My understanding of the current executor tree (please correct me if i'm wrong) is:

executor - requirements yet undefined
  one-way-executor - one-way & blocking
  two-way-executor - two-way & non-blocking

This would assume that the one-way executors are always blocking and the two-way executors are always non-blocking, we would like to argue for the one-way non-blocking case for situations where you want to provide a one-way fire and forget interface that does not block.

The rational is that emulating a one-way non-blocking executor on top of a one-way blocking executor would require launching an additional thread which will likely be inefficient and takes resources away from the underlying execution resource, and emulating a one-way non-blocking executor on top of a two-way non-blocking executor would require discarding the returned future which could potentially cause problems for handling exceptions caught by the future.

One option here could be to split the initial bifurcation of the executor tree by three rather than two:

executor - requirements yet undefined
  one-way-blocking-executor - one-way & blocking
  one-way-non-blocking-executor - one-way & non-blocking
  two-way-executor - two-way & non-blocking

**Comment by mjgarland** [comment]
One-way executors are not necessarily blocking.  The most basic OneWayExecutor category permits, but does not require, the executor to block the caller.  The EventExecutor, which refines OneWayExecutor and is meant to satisfy the needs of the Networking TS, provides one-way, non-blocking functionality.

Perhaps you could explain a bit more about your use case for non-blocking, one-way, bulk execution?

**Comment by jaredhoberock** [comment]
The paper doesn't currently define an executor customization point that has one-way, potentially non-blocking bulk execution semantics. In the current naming scheme, the name of such an operation would be `bulk_execute()`.

I'm not sure it makes sense to add another requirement to `BulkExecutor`. On the other hand, I don't see any reason not to introduce this new customization point, if it would satisfy your requirements. This would mean introducing the free function `execution::bulk_execute()`.

@fraggamuffin & @AerialMantis: What do you think?

**Comment by AerialMantis** [comment]
So our use case is an executor that supports the SYCL 1.2 specification, in which the parallel_for interface is a one-way non-blocking bulk execute function taking a range describing the work execution space. The reason for this interface is that work enqueueing is asynchronous yet scheduling performed implicitly based on data dependencies rather than explicitly via futures and continuations.

One option to support this could be to replace the requirements of sync_execute() with the requirements of execute() of the onewayexecutor category so it permits blocking or non blocking, is there a particular reason that the one way bulk execute function is blocking, would this cause conflicts with other requirements?

Another could be to add an additional execute() function in addition to sync_execute().

Another could be to have an additional customisation point as @jaredhoberock suggested though I'm not sure if would be ideal to implement the one way blocking sync_execute() with non blocking behaviour.

**Comment by fraggamuffin** [comment]
@jaredhoberock, @mjgarland, we like the one way non-blocking bulk_execute but can we fix it the same way as  @chriskohlhoff for execute() from spawn_execute() which became may or may not block

**Comment by jaredhoberock** [comment]
Right, the idea of the proposed `bulk_execute()` customization point is that it may or may not block, just like the `execute()` customization point.

**Comment by jaredhoberock** [comment]
Proposed resolution: introduce the customization point `execution::bulk_execute()` with the semantics discussed above.

**Comment by mjgarland** [comment]
Additionally:  BulkExecutor -> BulkTwoWayExecutor; create BulkOneWayExecutor categories.
