### ISSUE TITLE
Make reference counting behaviour and lifetimes of executors explicit

### ISSUE THREAD

**Issue by LeeHowes** [executors/issaquah_2016#34]
My understanding at this point is that executor lifetime is assumed to cover the entire execution in question. I don't know if this is the best answer, but it seems to be the direction people are going in. In that case we need to make that clear in this document.

The polymorphic wrapper on the other hand is copyable. Does it reference count the executor it owns? If we are always passing executors to places they are used by pointer, does the polymorphic wrapper need to be copyable at all? 

If the semantics of what it means to copy an executor vary too much between different executors we find it hard to see how a practical library can be generalised over executors.

**Comment by AerialMantis** [comment]
I would aggree here, I think it's very important for the minimal paper to specify the copy semantics of executors, I feel it will play a big part of designing the interface to come.

As the executor is the light weight object that is to be passed around, I feel that it should be copyable and since you may want to pass it to multiple control structure calls you would likely want the object to be shared. To support this it makes sense that the executor be reference counted and that any implementation of a control structure blocking or non-blocking maintains a reference to it for the duration of that execution.

Another alternate could be to have unique_executor and shared_executor wrappers that would be moveable and copyable respectively and those semantics would be reflected in overloads of the various control structures, though this approach may introduce more complexities in the design.

**Comment by LeeHowes** [comment]
The down side of reference counting is understanding when the destructor of the underlying resource will be cleaned up. It could easily end up blocking an internal thread if it is going to ensure that the underlying execution resource is flushed on a join.

In the discussions we had we discussed three use cases where this was a consideration:
* Use case 1: Network code, known thread transitions, only return a future at those network boundaries. Overhead of atomic ref counts will be trivial. Lifetime matters so better to pass executor by value and carry a ref count.
* Use case 2: Bulk synchronous style execution, parallel-for, most heterogeneous code that doesn't satisfy case 1. Execution strictly nested. Can safely pass executor by reference.
* Use case 3: Future.then chaining. Given that we can end up with ABA situations across executors A and B we clearly have lifetime considerations. However, because relatively small functions may be carried in executors overhead of the atomic matters.

Overall, we doubt that the overhead of reference counting really matters for cases 2 and 3. Lifetime of the execution resource is a very important question for those future chaining situations though.

**Comment by mjgarland** [comment]
Outcome of discussion on the teleconference:
- Rules for copying executors described in the paper should be written so that it is possible to implement reference counting executors
- Require that executor destructors shall not block pending completion of the submitted function objects

**Comment by fraggamuffin** [comment]
We like to revisit that last point as after discussion for us, we realize this will not work for us. For SYCL, because we have this fire-and-forget execution, there needs to be a live object that outlives the execution that can block on destruction until all the work completes. This means for SYCL to work with C++ executors, there needs to be an object in the interface that blocks on destruction. There are a few options: 
1. make the specification allow for may or may not block on destruction property for certain executors
2. make certain executors require to be constructed by a context/resource such that a context/resource can now block.  This requires the stop in the context/resource  in the destructor to be optional. SYCL destructor requires all currently enqueued work to either complete or fail.

**Comment by mjgarland** [comment]
I think the concern of blocking on destruction until work completes should belong to an execution context object as opposed to the executor.  That is more consistent with the idea that executors are relatively lightweight potentially short-lived objects as opposed to contexts which are likely to be long-lived.

**Comment by mjgarland** [comment]
Phone discussion:  having the context be responsible for blocking is fine.
