### ISSUE TITLE
Please add bulk_[*]_execute to thread pool

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#63]
Class thread_pool::executor_type
has the events and the following, but we would like it to add bulk, and the then variants.

 template<class Function>
      void sync_execute(Function&& f) const;

    template<class Function>
      future<result_of_t<decay_t<Function>()>>
        async_execute(Function&& f) const;

**Comment by mjgarland** [comment]
Do you want this for completeness or are you imagining something clever that those methods might do?

If you want this for completeness, it might be better to simply make sure that customization points like `execution::bulk_execute` have suitable fallbacks, because the fallback strategy would apply to every resource lacking that specific method rather than only extending `thread_pool` with a simple fallback.

**Comment by AerialMantis** [comment]
The reasoning behind this is that for our use case we need an execution resource which supports bulk execute, there's more details in issue #21. More specifically for SYCL we require an execution context to construct the executors as the execution context must block on destruction and must outlive the executors. Therefore we require the associated executor type to be capable of bulk execute.

I believe we discussed this in a previous call and decided that we should add the bulk execution functions.

**Comment by mjgarland** [comment]
Wouldn't a SYCL-enabled bulk execution context be a different type from `std::thread_pool` anyway, though?

**Comment by mjgarland** [comment]
Teleconference discussion:  Add these methods so that `thread_pool` illustrates the use of all the execution functions.

**Comment by jaredhoberock** [comment]
Fixed by #69
